apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcwebreactbd
  namespace: unitaire
  labels:
    app: GC.WebReact
    tier: database
spec:
  selector:
    matchLabels:
      app: GC.WebReact
      tier: database
  template:
    metadata:
      labels:
        app: GC.WebReact
        tier: database
    spec:
      containers:
      - name: gcwebreactbd
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secretsunitaire
                key: PASSWORD
          - name: ACCEPT_EULA
            valueFrom:
              configMapKeyRef:
                name: config-map-unitaire-bd
                key: TAA
        ports:
          - containerPort: 1433
        resources:
          limits:
            memory: "2Gi"
            cpu: "2"

---

apiVersion: v1
kind: Service
metadata:
  namespace: unitaire
  name: gcwebreactbd-service
  labels:
    app: GC.WebReact
    tier: database
spec:
  selector:
    app: GC.WebReact
    tier: database
  ports:
    - protocol: TCP
      port: 1433
  clusterIP: None
          