apiVersion: v1
kind: Deployment
metadata:
  name: gcwebreactBD
  namespace: unitaire
  labels:
    app: GC.WebReact
    tier: database
spec:
  selector:
    matchLabels:
      app: GC.WebReact
      tier: database
  template:
    metadata:
      labels:
        app: GC.WebReact
        tier: database
    spec:
      containers:
      - name: gcwebreactDB
        image: # à voir 
        resources:
          limits:
            memory: # à discuter
            cpu: # à discuter
          