apiVersion: v1
kind: Deployment
metadata:
  name: gcwebreactBD
  namespace: production
  labels:
    app: GC.WebReact
    tier: database
spec:
  selector:
    matchLabels:
      app: GC.WebReact
      tier: database
  template:
    metadata:
      labels:
        app: GC.WebReact
        tier: database
    spec:
      containers:
      - name: gcwebreactDB
        image: mysql:5.7
        environment: 
        MYSQL_DATABASE:
          valueFrom:
            secretKeyRef: 
              name: secretsProduction
              key: MYSQL_DATABASE
        MYSQL_ROOT_PASSWORD:
          valueFrom:
            secretKeyRef: 
              name: secretsProduction
              key: MYSQL_ROOT_PASSWORD
        MYSQL_USER:
          valueFrom:
            secretKeyRef: 
              name: secretsProduction
              key: MYSQL_USER
        MYSQL_PASSWORD:
           valueFrom:
            secretKeyRef: 
              name: secretsProduction
              key: MYSQL_PASSWORD
        resources:
          limits:
            memory: "2Gi"
            cpu: "2"
          