apiVersion: v1
kind: Secret
metadata:
  name: secrets-acceptation-webapp
data:
  CONNECTION_STRING: IlNlcnZlcj1nY3dlYnJlYWN0ZGIuYWNjZXB0YXRpb24uc3ZjLmNsdXN0ZXIubG9jYWw7RGF0YWJhc2U9YmRBY2NlcHRhdGlvbjtVc2VyPWFjY2VwdGF0aW9uO1Bhc3N3b3JkPXNydmJkOyI=
