apiVersion : apps/v1
kind: Deployment
metadata: 
  name: gcwebreactapp
  namespace: acceptation
  labels: 
    app: GC.WebReact
    tier: web
spec:
  selector:
    matchLabels:
        app: GC.WebReact
      tier: web
  template:
    metadata:
     labels:
       app: GC.WebReact
       tier: web
    spec:
      containers:
      - name: gcwebreactapp
        image: 5gtp3pp3r/image-webapp-tp3
        env:
        - name: ASPNETCORE_URLS
          value: 
          valueFrom:
            secretKeyRef:
              name: config-map-acceptation-web
              key: ASPNETCORE_URLS
        - name: ConnectionStrings__DefaultConnection
          value: 
          valueFrom:
            configMapKeyRef:
              name: secrets-acceptation-webapp
              key: CONNECTION_STRING
     
---

apiVersion: v1
kind: Service
metadata: 
  namespace: acceptation
  name: webapp-service
  labels:
    app: GC.WebReact
    tier: web
spec:
  selector:
    app: GC.WebReact
    tier: web
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30001 
  type: NodePort