apiVersion : v1
kind: Deployment
metadata: 
  name: gcwebreactApp
  namespace: production
  labels: 
    app: GC.WebReact
    tier: web
spec:
  selector:
    matchLabels:
      app: GC.WebReact
      tier: web
  template:
    metadata:
     labels:
       app: GC.WebReact
       tier: web
    spec:
      containers:
      - name: gcwebreactApp
        image: image-webapp-tp3
        env:
        - name: ASPNETCORE_URLS
          value: "http://0.0.0.0:30002"
