apiVersion : v1
kind: Deployment
metadata: 
  name: gcwebreactAppProduction
  namespace: production
  labels: 
    app: GC.WebReact
    tier: web
spec:
  selector:
    matchLabels:
      app: GC.WebReact
      tier: web
  template:
    metadata:
     labels:
       app: GC.WebReact
       tier: web
    spec:
      containers:
      - name: gcwebreactAppProduction
        image: #nom de l'image à willino
        volumeMounts:
        - name: #nom à venir
        - mounthPath: # je crois que le chemin dépend de l'image..
        volumes:
        - name: #nom à venir
          persistantVolumeClaim:
           claimName: #nom à venir
        ports:
        - containerPort: 80

      