apiVersion : apps/v1
kind: Deployment
metadata: 
  name: gcwebreactapp
  namespace: unitaire
  labels: 
    app: GC.WebReact
    tier: web
spec:
  selector:
    matchLabels:
      app: GC.WebReact
      tier: web
  template:
    metadata:
     labels:
       app: GC.WebReact
       tier: web
    spec:
      containers:
      - name: gcwebreactapp
        image: image-webapp-tp3
        env:
        - name: ASPNETCORE_URLS
          value: 
          valueFrom:
            secretKeyRef:
              name: config-map-unitaire-web
              key: ASPNETCORE_URLS
        - name: ConnectionStrings__DefaultConnection
          value: 
          valueFrom:
            configMapKeyRef:
              name: secrets-unitaire-webapp
              key: CONNECTION_STRING

---

apiVersion: v1
kind: Service
metadata: 
  namespace: unitaire
  name: webapp-service
  labels:
    app: GC.WebReact
    tier: web
spec:
  selector:
    app: GC.WebReact
    tier: web
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30000  
  type: NodePort
